# Generated by Django 2.2.1 on 2019-06-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_images_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('det_text', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('date_create', models.DateField(auto_now=True)),
            ],
        ),
    ]
