# Generated by Django 2.2.1 on 2019-07-01 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='reviews',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('date_create', models.DateField(auto_now=True)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('text', models.TextField()),
                ('catalog_items', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='panel.Product')),
                ('tags', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='panel.Tags')),
            ],
        ),
    ]
