# Generated by Django 2.2.1 on 2019-07-01 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_auto_20190701_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='catalog_items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.Product'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.Tags'),
        ),
    ]
