# Generated by Django 2.2.1 on 2019-07-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0012_auto_20190701_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='catalog_items',
        ),
        migrations.AddField(
            model_name='articles',
            name='catalog_items',
            field=models.ManyToManyField(blank=True, null=True, to='panel.Product'),
        ),
        migrations.RemoveField(
            model_name='articles',
            name='tags',
        ),
        migrations.AddField(
            model_name='articles',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='panel.Tags'),
        ),
    ]
